package com.revpay.model.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.*;
import lombok.*;

import java.math.BigDecimal;

/**
 * Request DTO for initiating a financial transaction between accounts.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TransactionRequest {

    @NotBlank(message = "Receiver identifier (Email or Phone) is required")
    private String receiverIdentifier;

    @NotNull(message = "Transaction amount is required")
    @DecimalMin(value = "1.00", message = "Minimum transaction amount is ₹1.00")
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private BigDecimal amount;

    @Size(max = 255, message = "Description cannot exceed 255 characters")
    private String description;

    @NotBlank(message = "Transaction PIN is required")
    @Pattern(regexp = "^[0-9]{4,6}$", message = "PIN must be between 4 and 6 digits")
    @ToString.Exclude // Crucial for security auditing
    private String transactionPin;

    /**
     * Unique key generated by the client to prevent duplicate transactions on retry.
     */
    @NotBlank(message = "Idempotency key is required for financial safety")
    private String idempotencyKey;

    @Builder.Default
    private String currency = "INR";
}