package com.revpay.controller;

import com.revpay.model.dto.ApiResponse;
import com.revpay.model.entity.Invoice;
import com.revpay.service.InvoiceService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.security.Principal;

import java.math.BigDecimal;
import java.time.LocalDate;

@Slf4j
@RestController
@RequestMapping("/api/v1/business")
@RequiredArgsConstructor
@PreAuthorize("hasAnyRole('BUSINESS', 'ADMIN')") // Secures all endpoints in this controller
@Tag(name = "Business Invoicing", description = "Endpoints for businesses to create and manage customer invoices")
public class InvoiceController {

    private final InvoiceService invoiceService;

    // --- DTOs (Defined directly in the controller for scoped use) ---

    public record InvoiceDTO(Long id, Long businessId, String customerName, String customerEmail, BigDecimal totalAmount, LocalDate dueDate, String status) {}

    // Request DTO to prevent Mass Assignment vulnerabilities (No description field)
    public record InvoiceCreateRequest(
            @NotBlank(message = "Customer name is required") String customerName,
            @Email @NotBlank(message = "Valid customer email is required") String customerEmail,
            @NotNull @Positive(message = "Amount must be greater than zero") BigDecimal totalAmount,
            @NotNull LocalDate dueDate) {}

    // --- ENDPOINTS ---

    @PostMapping("/invoices")
    @Operation(summary = "Create a new invoice", description = "Generates a new invoice for a customer linked to the logged-in business profile.")
    public ResponseEntity<ApiResponse<InvoiceDTO>> create(
            Principal principal, // ADDED: Grabs the logged-in user securely
            @Valid @RequestBody InvoiceCreateRequest request) {

        // The JWT Filter sets the email as the Principal name automatically
        String loggedInEmail = principal.getName();

        log.info("Business User: {} is creating a new invoice for {}", loggedInEmail, request.customerEmail());

        // Securely map the validated DTO to the Entity before passing to the service
        Invoice invoice = new Invoice();
        invoice.setCustomerName(request.customerName());
        invoice.setCustomerEmail(request.customerEmail());
        invoice.setTotalAmount(request.totalAmount());
        invoice.setDueDate(request.dueDate());

        // FIXED: Pass the email instead of the profileId
        Invoice created = invoiceService.createInvoice(loggedInEmail, invoice);

        InvoiceDTO dto = new InvoiceDTO(
                created.getId(),
                created.getBusinessProfile().getProfileId(),
                created.getCustomerName(),
                created.getCustomerEmail(),
                created.getTotalAmount(),
                created.getDueDate(),
                created.getStatus().name()
        );

        log.info("Invoice ID: {} created successfully.", created.getId());
        return ResponseEntity.ok(ApiResponse.success(dto, "Invoice created successfully"));
    }

    @GetMapping("/{profileId}/invoices")
    @Operation(summary = "Get business invoices", description = "Retrieves a paginated list of all invoices generated by a specific business.")
    public ResponseEntity<ApiResponse<Page<InvoiceDTO>>> getInvoices(
            @Parameter(description = "ID of the business profile") @PathVariable Long profileId,
            @PageableDefault(size = 10) Pageable pageable) {

        log.debug("Fetching invoices for business ID: {}. Page: {}, Size: {}", profileId, pageable.getPageNumber(), pageable.getPageSize());

        Page<Invoice> invoices = invoiceService.getAllInvoicesByBusiness(profileId, pageable);

        Page<InvoiceDTO> dtos = invoices.map(i -> new InvoiceDTO(
                i.getId(),
                i.getBusinessProfile().getProfileId(),
                i.getCustomerName(),
                i.getCustomerEmail(),
                i.getTotalAmount(),
                i.getDueDate(),
                i.getStatus().name()
        ));

        return ResponseEntity.ok(ApiResponse.success(dtos, "Invoices retrieved successfully"));
    }

    @PatchMapping("/invoices/{id}/pay")
    @Operation(summary = "Mark invoice as paid", description = "Manually updates the status of an invoice to PAID.")
    public ResponseEntity<ApiResponse<String>> markPaid(
            @Parameter(description = "ID of the invoice to update") @PathVariable Long id) {

        log.info("Manual status override: Marking invoice ID: {} as PAID", id);

        invoiceService.markAsPaid(id);

        return ResponseEntity.ok(ApiResponse.success(null, "Invoice updated to PAID status"));
    }
}