management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=revpay-core
management.metrics.export.prometheus.enabled=true
server.tomcat.threads.max=200
server.tomcat.accept-count=100
spring.lifecycle.timeout-per-shutdown-phase=30s